#!/bin/bash

#PBS -N TrainDreamBooth
#PBS -q normal
#PBS -l select=1:mem=64G:ngpus=1
#PBS -l walltime=12:00:00
#PBS -P Personal
#PBS -o out-run.txt
#PBS -e errors.txt

source activate nndl

MODEL_NAME="CompVis/stable-diffusion-v1-4"
TRAIN_DATA_DIR="Fazzie/Teyvat"
OUTPUT_DIR="scratch/colossalai/ColossalAI/examples/images/dreambooth/weight_output"

python /home/users/nus/e1216290/scratch/colossalai/ColossalAI/examples/images/dreambooth/inference.py
